# Generated by Django 5.0.7 on 2025-12-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_branch_created_at_branch_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='schedule',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
