# Generated by Django 5.1.15 on 2026-04-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_store_remove_product_branch_product_store_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
