# Generated by Django 5.1.15 on 2026-04-28 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_product_expiry_date_product_stock_alert_threshold_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='products.sellerstore')),
            ],
            options={
                'unique_together': {('store', 'name')},
            },
        ),
    ]
