# Generated by Django 5.1.15 on 2026-06-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='order_status',
            field=models.CharField(choices=[('received', 'Received'), ('packed', 'Packed'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='received', max_length=20),
        ),
    ]
